### ISSUE TITLE
Company mode display seems off

### ISSUE THREAD

**Issue by wpcarro** [hlissner/emacs-doom-themes#81]
First off, I love these themes and I appreciate all the hard work that goes into them. I'm trying to ensure that I'm loading my themes properly. It seems that my company mode, while sharing some of the colors of my loaded themes, is not styled appropriately. Here's a screenshot of what I'm looking at:

<img width="320" alt="screen shot 2017-07-01 at 8 52 14 pm" src="https://user-images.githubusercontent.com/13058701/27766489-50251110-5e9f-11e7-913c-468e7e817bc8.png">

Here's my config:

```elisp
(use-package doom-themes
  :ensure t
  :config
  (setq doom-themes-enable-bold nil
        doom-themes-enable-italic nil)
  (load-theme 'doom-molokai)
  (doom-themes-visual-bell-config)
  (doom-themes-neotree-config))
```

If this is the way it is designed to look, that's fine. I want to ensure that I'm not doing something wrong first.

**Comment by hlissner** [comment]
That is certainly a bug, but I am unable to reproduce it.

Could you add this to your config (after the `load-theme` call):

```emacs-lisp
(set-face-attribute 'tooltip nil :inherit nil :background "#21242b" :foreground "#bbc2cf")
```

If that works, then I know what to fix. If it doesn't, run the following and tell me what each face's `Background` color is:

+ `M-x describe-face RET tooltip`
+ `M-x describe-face RET company-tooltip`

**Comment by wpcarro** [comment]
Here is the output of `M-x describe-face RET tooltip`:

```
Face: tooltip (sample) (customize this face)

Documentation:
Face for tooltips.

Defined in ‘tooltip.el’.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: #bbc2cf
DistantForeground: unspecified
       Background: #21242b
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: t
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: nil
```

Here is the output of `M-x describe-face RET company-tooltip`:

```
Face: company-tooltip (sample) (customize this face)

Documentation:
Face used for the tooltip.

Defined in ‘company.el’.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: #515151
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: tooltip

[back]
```
